prdcr_listen_add name=computes regex=sampler.*
prdcr_listen_start name=computes 

updtr_add name=all_sets interval=1s offset=100ms
updtr_prdcr_add name=all_sets regex=.*
updtr_start name=all_sets 

load name=store_csv
config name=store_csv path=/home/ubuntu/ldms-csv

strgp_add name=csv_store plugin=store_csv container=ldms_data schema=meminfo
strgp_prdcr_add name=csv_store regex=.*
strgp_start name=csv_store