advertiser_add name=agg11 xprt=sock host=aggregator.cluster.internal port=10444 reconnect=10s  
advertiser_start name=agg11

load name=meminfo  
config name=meminfo producer=samplerd-2 instance=samplerd-2/meminfo  
start name=meminfo interval=1s