advertiser_add name=agg xprt=sock host=aggregator port=10444 reconnect=10s
advertiser_start name=agg

load name=meminfo
config name=meminfo producer=__NODE__ instance=__NODE__/meminfo
start name=meminfo interval=1s
