advertiser_add name=agg xprt=sock host=aggregator.app.internal port=10444 reconnect=10s
advertiser_start name=agg

load name=meminfo
config name=meminfo producer=__NODE__ instance=__NODE__/meminfo
start name=meminfo interval=1s

load name=vmstat
config name=vmstat producer=__NODE__ instance=__NODE__/vmstat
start name=vmstat interval=1s

load name=procstat
config name=procstat producer=__NODE__ instance=__NODE__/procstat
start name=procstat interval=1s
